### ISSUE TITLE
having issues

### ISSUE THREAD

**Issue by HarshitAnchan** [mejaz/imaginai#1]
![image](https://github.com/mejaz/imaginai/assets/88927163/3a553a00-43f2-44e6-85f3-0ed461e90d21)

having issues while generating the image 

websocket.js:61 WebSocket connection to 'ws://localhost:3000/_next/webpack-hmr' failed:

**Comment by mejaz** [comment]
Hi,

You may check if you have put the OPENAI_API_KEY in the .env.local file.
And please also check if you have credits in your OpenAI account.

Let me know if it works.

Thanks,
Ejaz

**Comment by HarshitAnchan** [comment]
yup i have added the api key but the thing is i have 0 credits in openAI
